
function read_folder_names()
    vector_folder_names = [
    "SEE_Primavera__25MW";
    "SEE_Verano__25MW";
    "SEE_Otono__25MW";
    "SEE_Invierno__25MW";
    "SEE_Primavera_1GW_equal";
    "SEE_Verano_1GW_equal";
    "SEE_Otono_1GW_equal";
    "SEE_Invierno_1GW_equal";
    "SEE_Primavera_5GW_equal";
    "SEE_Verano_5GW_equal";
    "SEE_Otono_5GW_equal";
    "SEE_Invierno_5GW_equal";
    "SEE_Primavera_10GW_equal";
    "SEE_Verano_10GW_equal";
    "SEE_Otono_10GW_equal";
    "SEE_Invierno_10GW_equal";
    "SEE_Primavera_12_5GW_equal";
    "SEE_Verano_12_5GW_equal";
    "SEE_Otono_12_5GW_equal";
    "SEE_Invierno_12_5GW_equal";
    "SEE_Primavera_15GW_equal";
    "SEE_Verano_15GW_equal";
    "SEE_Otono_15GW_equal";
    "SEE_Invierno_15GW_equal";
    "SEE_Primavera_20GW_equal";
    "SEE_Verano_20GW_equal";
    "SEE_Otono_20GW_equal";
    "SEE_Invierno_20GW_equal";
    "SEE_Primavera_22_5GW_equal";
    "SEE_Verano_22_5GW_equal";
    "SEE_Otono_22_5GW_equal";
    "SEE_Invierno_22_5GW_equal";
    "SEE_Primavera_1GW_Pcurt";
    "SEE_Verano_1GW_Pcurt";
    "SEE_Otono_1GW_Pcurt";
    "SEE_Invierno_1GW_Pcurt";
    "SEE_Primavera_5GW_Pcurt";
    "SEE_Verano_5GW_Pcurt";
    "SEE_Otono_5GW_Pcurt";
    "SEE_Invierno_5GW_Pcurt";
    "SEE_Primavera_10GW_Pcurt";
    "SEE_Verano_10GW_Pcurt";
    "SEE_Otono_10GW_Pcurt";
    "SEE_Invierno_10GW_Pcurt";
    "SEE_Primavera_12_5GW_Pcurt";
    "SEE_Verano_12_5GW_Pcurt";
    "SEE_Otono_12_5GW_Pcurt";
    "SEE_Invierno_12_5GW_Pcurt";
    "SEE_Primavera_15GW_Pcurt";
    "SEE_Verano_15GW_Pcurt";
    "SEE_Otono_15GW_Pcurt";
    "SEE_Invierno_15GW_Pcurt";
    "SEE_Primavera_20GW_Pcurt";
    "SEE_Verano_20GW_Pcurt";
    "SEE_Otono_20GW_Pcurt";
    "SEE_Invierno_20GW_Pcurt";
    "SEE_Primavera_22_5GW_Pcurt";
    "SEE_Verano_22_5GW_Pcurt";
    "SEE_Otono_22_5GW_Pcurt";
    "SEE_Invierno_22_5GW_Pcurt"
    ]
    return vector_folder_names
end

# vector_folder_names = [
#     "SEE_Invierno__25MW";
#     "SEE_Invierno_1GW_equal";
#     "SEE_Invierno_1GW_Pcurt";
#     "SEE_Invierno_5GW_equal";
#     "SEE_Invierno_5GW_Pcurt";
#     "SEE_Invierno_10GW_equal";
#     "SEE_Invierno_10GW_Pcurt";
#     "SEE_Invierno_12_5GW_equal";
#     "SEE_Invierno_12_5GW_Pcurt";
#     "SEE_Invierno_15GW_equal";
#     "SEE_Invierno_15GW_Pcurt";
#     "SEE_Invierno_20GW_equal";
#     "SEE_Invierno_20GW_Pcurt";
#     "SEE_Invierno_22_5GW_equal";
#     "SEE_Invierno_22_5GW_Pcurt";
#     "SEE_Otono__25MW";
#     "SEE_Otono_1GW_equal";
#     "SEE_Otono_1GW_Pcurt";
#     "SEE_Otono_5GW_equal";
#     "SEE_Otono_5GW_Pcurt";
#     "SEE_Otono_10GW_equal";
#     "SEE_Otono_10GW_Pcurt";
#     "SEE_Otono_12_5GW_equal";
#     "SEE_Otono_12_5GW_Pcurt";
#     "SEE_Otono_15GW_equal";
#     "SEE_Otono_15GW_Pcurt";
#     "SEE_Otono_20GW_equal";
#     "SEE_Otono_20GW_Pcurt";
#     "SEE_Otono_22_5GW_equal";
#     "SEE_Otono_22_5GW_Pcurt";
#     "SEE_Primavera__25MW";
#     "SEE_Primavera_1GW_equal";
#     "SEE_Primavera_1GW_Pcurt";
#     "SEE_Primavera_5GW_equal";
#     "SEE_Primavera_5GW_Pcurt";
#     "SEE_Primavera_10GW_equal";
#     "SEE_Primavera_10GW_Pcurt";
#     "SEE_Primavera_12_5GW_equal";
#     "SEE_Primavera_12_5GW_Pcurt";
#     "SEE_Primavera_15GW_equal";
#     "SEE_Primavera_15GW_Pcurt";
#     "SEE_Primavera_20GW_equal";
#     "SEE_Primavera_20GW_Pcurt";
#     "SEE_Primavera_22_5GW_equal";
#     "SEE_Primavera_22_5GW_Pcurt";
#     "SEE_Verano__25MW";
#     "SEE_Verano_1GW_equal";
#     "SEE_Verano_1GW_Pcurt";
#     "SEE_Verano_5GW_equal";
#     "SEE_Verano_5GW_Pcurt";
#     "SEE_Verano_10GW_equal";
#     "SEE_Verano_10GW_Pcurt";
#     "SEE_Verano_12_5GW_equal";
#     "SEE_Verano_12_5GW_Pcurt";
#     "SEE_Verano_15GW_equal";
#     "SEE_Verano_15GW_Pcurt";
#     "SEE_Verano_20GW_equal";
#     "SEE_Verano_20GW_Pcurt";
#     "SEE_Verano_22_5GW_equal";
#     "SEE_Verano_22_5GW_Pcurt"
# ]